//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AaAppsView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_AABACKGROUNDVIEW_H)
#define _AABACKGROUNDVIEW_H

#include <gkGameObject.h>
#include "Rootview.h"
#include "AaViewport.h"
#include "DataBaseImpl.h"

class AaAppsView:public RootView 
{
public:
	AaAppsView();
	~AaAppsView();
	DataBaseImpl* getDataBase();
	ViewNode* getParentNode();
	void setMoveVector(gkVector3 gVector);		// 设置AA的移动向量
	
	virtual bool setFocus(ViewNode* node);
	virtual bool setFocus(int vindex);
	virtual void loseViewFocus() = 0;
private:
	virtual void showView();
	virtual void hideView();
private:
	AaViewport* m_pAaViewPort;
	ViewNode* m_pParentNode;
	static DataBaseImpl* m_pDataBase;
};

#endif  //_AABACKGROUNDVIEW_H
