//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AaResidentView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "AaResidentView.h"
#include "ViewNode.h"
#include "Aabridge.h"

#define _AARESIDENT_SHOP_NAME_	"Plane_v06"
#define _AARESIDENT_TV_NAME_	"Plane_v07"
#define _AARESIDENT_SORT_NAME_	"Plane_v11"

#define _AARESIDENT_SORT_ANM_	"Plane_v11Action"
#define _AARESIDENT_SORT_TEX_ANM_ "Plane_v11Action.001"

#define _AARST_SANM_ENTER_START_	587
#define _AARST_SANM_ENTER_END_		607
#define _AARST_SANM_EXIT_START_		700
#define _AARST_SANM_EXIT_END_		715

// #define _AARESIDENT_ENTER_SORT_TEX_ANM_START_ 590
// #define _AARESIDENT_ENTER_SORT_TEX_ANM_END_ 610
// #define _AARESIDENT_QUIT_SORT_TEX_ANM_START_ 700
// #define _AARESIDENT_QUIT_SORT_TEX_ANM_END_ 720

#define _AAREDIDENT_NODE_NUM_	3

#define _AAREDIDENT_COLO_NUM_	2

AaResidentView::AaResidentView() :RootView(false),m_ppViewNodeList(NULL),m_StVisible(false),m_pSortAnm(NULL), m_pSortTexAnm(NULL)
{
	m_ppViewNodeList = getViewNodeList();
	setViewNodeNum(_AAREDIDENT_NODE_NUM_);

	m_ppViewNodeList = new ViewNode*[_AAREDIDENT_NODE_NUM_];
	m_ppViewNodeList[0] = (new ViewNode(Aabridge::getScene(),_AARESIDENT_SHOP_NAME_))->setIndex(0,0);
	m_ppViewNodeList[1] = (new ViewNode(Aabridge::getScene(),_AARESIDENT_TV_NAME_))->setIndex(1,1);
	m_ppViewNodeList[2] = (new ViewNode(Aabridge::getScene(),_AARESIDENT_SORT_NAME_))->setIndex(2,3);

//	m_ppViewNodeList[2]->getGameObj()->setVisible(false);
	setViewNodeList(m_ppViewNodeList);

	m_pSortAnm = new BlenderAnimation(Aabridge::getScene(),m_ppViewNodeList[2]->getGameObj(),_AARESIDENT_SORT_ANM_);
	m_pSortTexAnm = new BlenderAnimation(Aabridge::getScene(),m_ppViewNodeList[2]->getGameObj(),_AARESIDENT_SORT_TEX_ANM_);
}

AaResidentView::~AaResidentView()
{
	
	m_ppViewNodeList = NULL;
	ui_delete(m_pSortAnm);
	ui_delete(m_pSortTexAnm);
	m_pSortTexAnm = NULL;
	m_pSortAnm = NULL;
}

bool 
AaResidentView::isHitTvButton(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppViewNodeList[1]->getGameObj());
}

bool 
AaResidentView::isHitAppMarketButton(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppViewNodeList[0]->getGameObj());
}

bool 
AaResidentView::isHitSortButton(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppViewNodeList[2]->getGameObj());
}

bool 
AaResidentView::isFocusOnTvButton()
{
	return getFocus() == m_ppViewNodeList[1];
}

bool 
AaResidentView::isFocusOnMarket()
{
	return getFocus() == m_ppViewNodeList[0];
}

bool 
AaResidentView::isFocusOnSortButton()
{
	return getFocus() == m_ppViewNodeList[2];
}

bool 
AaResidentView::setFocus(ViewNode* node,bool isCircle)
{
	if (node != m_ppViewNodeList[2])
		return RootView::setFocus(node,true);
	return RootView::setFocus(node);
}

bool 
AaResidentView::setFocus(int index,bool isCircle)
{
	if (index != 2)
	{
		return RootView::setFocus(index,true);
	}
	return RootView::setFocus(index);
}

void 
AaResidentView::loseViewFocus()
{

}
void 
AaResidentView::showView()
{
	_ASSERT_(m_pSortAnm);
	_ASSERT_(m_pSortTexAnm);
	
	m_pSortAnm->setFrameScope(_AARST_SANM_ENTER_START_, _AARST_SANM_ENTER_END_);
	m_pSortAnm->play();

 	m_pSortTexAnm->setFrameScope(590, 610);
 	m_pSortTexAnm->play();
}

void 
AaResidentView::hideView()
{
	_ASSERT_(m_pSortAnm);
	_ASSERT_(m_pSortTexAnm);
	m_pSortAnm->setFrameScope(_AARST_SANM_EXIT_START_,_AARST_SANM_EXIT_END_);
	m_pSortAnm->play();

 	m_pSortTexAnm->setFrameScope(700, 720);
 	m_pSortTexAnm->play();
}