//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AaResidentView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_AARESIDENTVIEW_H)
#define _AARESIDENTVIEW_H

#include "RootView.h"

class BlenderAnimation;
class AaResidentView :public RootView
{
public:
	AaResidentView();
	~AaResidentView();
	bool isHitTvButton(Ogre::RaySceneQueryResult& objArray);
	bool isHitAppMarketButton(Ogre::RaySceneQueryResult& objArray);
	bool isHitSortButton(Ogre::RaySceneQueryResult& objArray);
	bool isFocusOnTvButton();
	bool isFocusOnMarket();
	bool isFocusOnSortButton();
	virtual bool setFocus(ViewNode* node,bool isCircle = false);
	virtual bool setFocus(int index,bool isCircle = false);

	virtual void loseViewFocus();
private:
	virtual void showView();
	virtual void hideView();
private:
	ViewNode** m_ppViewNodeList;
	BlenderAnimation* m_pSortAnm;
	BlenderAnimation* m_pSortTexAnm;
	bool m_StVisible;		// SortTypeVisible
};

#endif  //_AARESIDENTVIEW_H
