//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Aaview.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "Aaview.h"
#include "AppsViewUtil.h"
#include "AaViewImpl.h"
#include "GameObjMaker.h"

Aaview::Aaview():AaAppsView("AaViewAnm")
{
//	GameObjMaker::adjustGameObjPos(getDataBase()->getAppsVector(),getParentNode()->getGameObj());

}

Aaview::~Aaview() 
{

}

void 
Aaview::showView()
{
	AppsViewUtil::getInstance()->reset();
	getParentNode()->getGameObj()->getNode()->_update(true,false);
	//setFocus(0);
	tidyApps();
	GameObjMaker::adjustGameObjPos(AaViewImpl::getInstance()->getAppsList(),getParentNode()->getGameObj());
	setFocus(0);
	//AaAppsView::showView();
}

void 
Aaview::tidyApps()
{
	vector<AppUnit*>* pVector = AaViewImpl::getInstance()->getAppsList();
	if(!pVector)
		return;
	int size = pVector->size();
	AppUnit* pApp = NULL;
	for (int i = 0;i < size;i++)
	{
		pApp = pVector->at(i);
		pApp->getGameObj()->setVisible(true);
		pApp->getGameObj()->setSubEntityVisible(_APP_CROSS_INDEX_,false);
		pApp->getGameObj()->setSubEntityVisible(_APP_X_INDEX_,false);
		pApp->getGameObj()->setSubEntityVisible(_APP_HEART_INDEX_,false);
	}
}

void 
Aaview::setUninstallLogoVisible(ViewNode* pNode,bool flag)
{
	flag?showUninstallLogo(pNode):hideUninstallLogo(pNode);
}

void
Aaview::loseViewFocus()
{

}

void 
Aaview::showUninstallLogo(ViewNode* pNode)
{

}

void 
Aaview::hideUninstallLogo(ViewNode* pNode)
{

}