//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Aaview.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "AaViewImpl.h"
#include "AppsViewUtil.h"

AaViewImpl*	AaViewImpl::mInstance = NULL;
AaViewImpl::AaViewImpl() :m_isUninstallMode(false),m_pViewUtil(NULL)
{
	m_pAaView = new Aaview();
	setRootView(m_pAaView);
	setBackgroundView(m_pAaView);
	m_pAaView->setVisible(false);
	appSort(ST_DEFAULT);
	update();
	syncTextureFromJava();
	m_pAaView->setFocus(0);
	m_pViewUtil = AppsViewUtil::getInstance();
	mInstance = this;
	
}

AaViewImpl::~AaViewImpl() 
{
	ui_delete(m_pAaView);
}

AaViewImpl* 
AaViewImpl::getInstance()
{
	return mInstance?mInstance:new AaViewImpl();
}
void 
AaViewImpl::setUninstallAppMode(bool flag)
{
	if(m_isUninstallMode == flag)
		return;
	m_isUninstallMode = flag;
	int num = getAppNum();
	vector<AppUnit*>*  pvList = getAppsList();
	for (int i = 0;i<num;i++)
	{
		//if(ppList[i]->¿ÉÐ¶ÔØ)
		{
			m_pAaView->setUninstallLogoVisible((*pvList)[i],flag);
		}
	}
}

bool 
AaViewImpl::isUninstallAppMode()
{
	return m_isUninstallMode;
}

AppUnit* 
AaViewImpl::getCurrentApp()
{
	return (AppUnit*)(m_pAaView->getFocus());
}

AppUnit* 
AaViewImpl::isHitApp_AA(Ogre::RaySceneQueryResult& objArray)
{
	return (AppUnit*)(m_pAaView->isHitViewNode(objArray));
}

//bool 
//AaViewImpl::moveFocus(eFlyDirection direct)	// ÒÆ¶¯focus
//{
//	return true;//m_pAaView->moveFocus(direct);
//}

		
void 
AaViewImpl::onClickViewNode(ViewNode* pApp)
{

}

void 
AaViewImpl::onHitCurrentNode()			// 
{

}

void 
AaViewImpl::onLoseFocus()
{

}