//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AaViewport.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//

#include <gkWindow.h>
#include "AaViewport.h"
#include "Aabridge.h"
#include "OgreViewport.h"
#include "OgreSceneManager.h"

using namespace Ogre;

#define _SUBCAMERA_NAME		"Camera_test01"

AaViewport::AaViewport(bool vsb) :m_pSubCamera(NULL),m_pViewPort(NULL)
{
	_ASSERT_(Aabridge::getScene());
	float windowWidth = Aabridge::getScene()->getDisplayWindow()->getRequestedWidth();
	float windowHeight = Aabridge::getScene()->getDisplayWindow()->getRequestedHeight();
	Aabridge::getScene()->getManager()->setScissorRect(vsb,windowWidth*_CLIP_TOP_X_, _CLIP_TOP_Y_, windowWidth - 20, windowHeight - _CLIP_TOP_Y_);
}

AaViewport::~AaViewport() 
{
	if(m_pViewPort)
		Aabridge::getScene()->DeleteSubScene(m_pViewPort);
}

void 
AaViewport::setViewportEnable(bool vsb)
{
	Aabridge::getScene()->getManager()->setScissorEnable(vsb);
}

Ogre::Viewport* 
AaViewport::getViewPort()
{
	return m_pViewPort;
}