//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AaViewport.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_AAVIEWPORT_H)
#define _AAVIEWPORT_H

#include<gkCamera.h>

class AaViewport {
public:
	AaViewport(bool vsb = true);
	~AaViewport();
	void setViewportEnable(bool vsb = true);
	Ogre::Viewport* getViewPort();
private:
	gkCamera* m_pSubCamera;
	Ogre::Viewport* m_pViewPort;
};

#endif  //_AAVIEWPORT_H
