//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Aaview.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_AAVIEW_H)
#define _AAVIEW_H

#include "AaAppsView.h"

class Aaview :public AaAppsView
{
public:
	Aaview();
	~Aaview();
	void setUninstallLogoVisible(ViewNode* pNode,bool flag = true);
	virtual void loseViewFocus();
private:
	virtual void showView();
	void tidyApps();	// 整理应用，将该隐藏的subentity隐藏
private:
	void showUninstallLogo(ViewNode* pNode);
	void hideUninstallLogo(ViewNode* pNode);
};

#endif  //_AAVIEW_H
