//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AppUnitShortcut.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "AppUnitShortcut.h"
#include "gkEntity.h"

#define _SHORTCUR_ICON_SENTITY_	1
#define _SHORTCUR_NAME_SENTITY_	2
AppUnitShortcut::AppUnitShortcut(gkScene*pScene,const gkHashedString& str,AppUnit* pApp,bool nail):
		ViewNode(pScene,str),mIconTextureID(0),mNameTextureID(0)
{
	m_pApp = pApp;

	gkGameObject* pObj = getGameObj();
	m_isNailApp = nail;
	if(pObj&&pObj->getSubEntitiesNum() > 4)
	{
		//int iconIndex = pObj->getEntity()->getSEntityIndexByMatIndex(_SHORTCUR_ICON_SENTITY_);
		//int nameIndex = pObj->getEntity()->getSEntityIndexByMatIndex(_SHORTCUR_NAME_SENTITY_);
		mIconTextureID = ((gkEntity*)pObj)->getGLTextureID(_SHORTCUR_ICON_SENTITY_,0);
		mNameTextureID = ((gkEntity*)pObj)->getGLTextureID(_SHORTCUR_NAME_SENTITY_,0);
		return;
	}
	
}

AppUnitShortcut* 
AppUnitShortcut::setIndex(int i0,int i1)
{
	m_MinIndex = i0;
	m_MaxIndex = i1;
//	m_pIndex[0] = m_MinIndex;
//	m_pIndex[1] = m_MaxIndex;
	return this;
}

void 
AppUnitShortcut::setApp(AppUnit* pApp)
{
	m_pApp = pApp;
}

AppUnit* 
AppUnitShortcut::getApp()
{
	return m_pApp;
}

bool 
AppUnitShortcut::syncTexture()
{
	gkGameObject* pObj  = getGameObj();
	if(!pObj || pObj->getSubEntitiesNum() < 5)
	{
		gkPrintf("shortcut syncTexture error! gameObj == NULL");
		return false;
	}

	((gkEntity*)pObj)->setGLTextureID(_SHORTCUR_ICON_SENTITY_,0,m_pApp?m_pApp->getAppIconTID():mIconTextureID);

	((gkEntity*)pObj)->setGLTextureID(_SHORTCUR_NAME_SENTITY_,0,m_pApp?m_pApp->getAppNameTID():mNameTextureID);
	return true;
}

bool 
AppUnitShortcut::isNailApp()
{
	return m_isNailApp;
}