//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AppUnitShortcut.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//



#if !defined(_APPUNITSHORTCUR_H)
#define _APPUNITSHORTCUR_H

#include "AppUnit.h"

using namespace tcl;

class AppUnitShortcut :public ViewNode
{
public:
	AppUnitShortcut(gkScene*pScene,const gkHashedString& str,AppUnit* pApp = NULL,bool nail = false);
	AppUnitShortcut* setIndex(int i0,int i1);
	void setApp(AppUnit* pApp);
	AppUnit* getApp();
	bool syncTexture();
	bool isNailApp();
private:
	AppUnit* m_pApp;
	int mIconTextureID;
	int mNameTextureID;
	bool m_isNailApp;
};

#endif  //_APPUNITSHORTCUR_H
