//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FocusMove N+.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_BLEANDERANIMATION_H)
#define _BLEANDERANIMATION_H


#include <gkScene.h>
#include <akCommon.h>
#include <gkGameObject.h>

class BlenderAnmInterface;
class BlenderAnimation {
public:
	BlenderAnimation(gkScene*,gkGameObject*,const gkHashedString& name,BlenderAnmInterface* pInterface = NULL);
	~BlenderAnimation();
	void setFrameTime(int time);
	bool setFrameScope(int start, int end);
	bool play(const akAnimationEvalMode& anmEvalMode = AK_ACT_END);
	bool isPlaying();
	void finishAnm();
	void setGameObj(gkGameObject* gameObj);
	void setAnmInterface(BlenderAnmInterface*);
	void  onAnmFinish(void);
	
private:
	gkScene*		   m_pScene;
	gkGameObject*	   m_pGameObj;
	gkAnimation*	   m_pAnm;
	gkAnimationPlayer* m_pAnmPlayer;
	BlenderAnmInterface* m_interface;
	akCallback* m_pCallback;
	int m_AnmStartFrame;
	int m_AnmEndFrame;
	bool m_isPlaying;
};

#endif  //_BLENDERANIMATION_H
