//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DataBaseImpl.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_DATABASEIMPL_H)
#define _DATABASEIMPL_H

#include "AppUnit.h"
#include <vector>

using namespace std;

class DataBaseImpl 
{
public:
	DataBaseImpl();
	~DataBaseImpl();
	vector<AppUnit*>* getAppsVector();
	AppUnit* getApp(int id);
	AppUnit* getNodeByVindex(unsigned int index);		// 根据AppUnit* 在vector中的序列进行检索
	AppUnit* getNodeByObjIndex(int index);				// 根据ViewNode的minindex&maxIndex 回去AppUnit

	void appInverted();
	void addApp(AppUnit* pApp);
	void removeApp(AppUnit* pApp);
	void updateApp(AppUnit* pApp);
	int getAppsNum();
	static DataBaseImpl* getInstance();
public:
	static vector<AppUnit*> m_AppsVector;
private:
	static DataBaseImpl* m_pThis;
	CDataService* m_pDataService;
};

#endif  //_DATABASEIMPL_H
