//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Recommand Block.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_FAVORITE_BLOCK_H)
#define _FAVORITE_BLOCK_H

#include "Block.h"

class FavoriteBlock :public Block
{
public:
	FavoriteBlock(gkScene*);
	~FavoriteBlock();
	virtual BlockEnum getBlockEnum(); 
	virtual int getMenuFlag();
	virtual int getVacantPosParentID();
protected:
	virtual void initEditMenu();
};

#endif  //_FAVORITE_BLOCK_H
