//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GameObjMaker.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_GAMEOBJMAKER_H)
#define _GAMEOBJMAKER_H

#include <gkGameObject.h>
#include "AppUnit.h"

class GameObjMaker 
{
public:
	static gkGameObject* makeGameObjByAppUnit(AppUnit* pApp,int name,gkGameObject* pObjTemplate = NULL);
	static gkVector3	getPosByIndex(int index);
	static void adjustGameObjPos(const std::vector<AppUnit*>* const pVector,gkGameObject* parent = NULL);
};

#endif  //_GAMEOBJMAKER_H
