//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HaResidentView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "HaResidentView.h"

HaResidentView::HaResidentView() 
{

}

HaResidentView::~HaResidentView() 
{

}

bool 
HaResidentView::isHitMovieButton()
{
	return false;
}

bool 
HaResidentView::isHitFavoriteButton()
{
	return false;
}

bool 
HaResidentView::isHitExitButton()
{
	return false;
}

void 
HaResidentView::loseViewFocus()
{

}