//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HaResidentViewImpl.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_HARESIDENTVIEWIMPL_H)
#define _HARESIDENTVIEWIMPL_H

#include "Aabridge.h"
#include "RootViewImpl.h"

class HaResidentView;
class HaResidentViewImpl :public RootViewImpl
{
public:
	HaResidentViewImpl();
	~HaResidentViewImpl();
	bool isHitMovieButton();
	bool isHitFavoriteButton();
	bool isHitExitButton();

	bool moveFocus(eFlyDirection direct);	// 移动focus
	bool MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction);
	bool setViewNodeFocus(ViewNode*);		// 设置viewNode* 为当前focus
	ViewNode* getCurrentViewNode();			
	void onClickViewNode(ViewNode*);
	void onLoseFocus();
	void onHitCurrentNode();
private:
	HaResidentView* m_pResidentView;
};

#endif  //_HARESIDENTVIEWIMPL_H
