//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HaSettingsView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_HASETTINGSVIEW_H)
#define _HASETTINGSVIEW_H

#include "AaAppsView.h"
#include "BlenderAnmInterface.h"

class Block;
class HaSettingsView:public AaAppsView,public BlenderAnmInterface
{
	friend class HaSettingsViewImpl;
public:
	HaSettingsView();
	~HaSettingsView();
	virtual void onTick(gkScalar time);
	virtual void loseViewFocus();
	void showWarningDialog();
	void hideWarningDialog();
protected:
	bool showNodeFlag(AppUnit* pNode);
	bool hideNodeFlag(AppUnit* pNode);
	void setBlockThumb(Block* pBlock);
	void showBlockThumb(Block* pBlock);
	void hideBlockThumb();
private:
	virtual void showView();
	virtual void hideView();
	void showCandidateApps();
	void onBlenderAnmFinish(BlenderAnimation* p,int s,int e);
private:
	ViewNode** m_ppViewNodeList;
	BlenderAnimation** m_ppBldAnmList;
	Block* m_pBlock;
	gkVector3 m_BlockParentRowPos;		// block父节点的父节点
	gkVector3 m_BlockParentRowScale;
	gkVector3 m_BlockRowPos;
	gkVector3 m_BlockRowScale;
	gkGameObject* m_pWarningDialog;
	BlenderAnimation** m_ppWarningDialogAnm;
	bool m_showWDialogOver;
};

#endif  //_HASETTINGSVIEW_H
