//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HaSettingsViewImpl.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_HASETTINGSVIEWIMPL_H)
#define _HASETTINGSVIEWIMPL_H

#include "AaAppsViewImpl.h"
#include "HaSettingsView.h"
#include "HaResidentView.h"

class HaSettingsViewImpl :public AaAppsViewImpl
{
	friend class HaSettingsView;
public:
	HaSettingsViewImpl();
	~HaSettingsViewImpl();
	static HaSettingsViewImpl* getInstance();
	virtual vector<AppUnit*>*  getAppsList();
	virtual void onTick(gkScalar time);
	AppUnit* isHitApp_HA(Ogre::RaySceneQueryResult& objArray);
	void setViewVisible(Block* pObj,bool vsb = true);

	//bool moveFocus(eFlyDirection direct);	// 移动focus
	bool MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction);		
	void onClickViewNode(ViewNode*);
	void onLoseFocus();
	bool setHomeAppTag(AppUnit* pApp);		// 如果pApp在Block中，则删除此应用，否则添加
protected:
	void syncAppVector();
private:
	Block* m_pBlock;
	HaSettingsView* m_pSettingsview;
	static HaSettingsViewImpl* mInstance;
	vector<AppUnit*>* m_pAppsVector;
};

#endif  //_HASETTINGSVIEWIMPL_H
