//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LetterViewImpl.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_LETTERVIEWIMPL_H)
#define _LETTERVIEWIMPL_H

#include "RootViewImpl.h"
#include "utSingleton.h"

class LetterView;
class AppsViewUtil;
class LetterViewImpl :public RootViewImpl,utSingleton<LetterViewImpl>
{
public:
	LetterViewImpl();
	~LetterViewImpl();
	//void setLetterViewVisible(bool v);
	//bool getLetterViewVisible();
	char getHitLetter(Ogre::RaySceneQueryResult& objArray);				// return NULL or ‘#’ or ‘A’~‘Z’
	char getCurrentLetter();			// 获取当前焦点所在的字母
	void setCurrentLetter(char chr);	// 设置点击到的字母

	bool moveFocus(eFlyDirection direct);	// 移动focus
	bool MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction);
	bool setViewNodeFocus(ViewNode*);		// 设置viewNode* 为当前focus
	ViewNode* getCurrentViewNode();			
	void onClickViewNode(ViewNode*);
	void onLoseFocus();
	void onHitCurrentNode();
	UT_DECLARE_SINGLETON(LetterViewImpl);
protected:
	char viewNodeToChar(ViewNode* pNode);
	ViewNode* charToViewNode(char ch);
private:
	LetterView* m_pLetterView;
	AppsViewUtil*	m_pViewUtil;
};

#endif  //_LETTERVIEWIMPL_H
