//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LetterView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//

#include "LetterView.h"
#include "Aabridge.h"
#include "ViewNode.h"
#include "BlenderAnimation.h"

#define _LV_VN_NUM_			26
//#define _LV_PARENT_NAME_	"Plane_vz01"
#define _LV_LETTER_A_		"Plane_vz01"
#define _LV_LETTER_B_		"Plane_vz02"
#define _LV_LETTER_C_		"Plane_vz03"
#define _LV_LETTER_D_		"Plane_vz04"
#define _LV_LETTER_E_		"Plane_vz05"
#define _LV_LETTER_F_		"Plane_vz06"
#define _LV_LETTER_G_		"Plane_vz07"
#define _LV_LETTER_H_		"Plane_vz08"
#define _LV_LETTER_I_		"Plane_vz09"
#define _LV_LETTER_J_		"Plane_vz10"
#define _LV_LETTER_K_		"Plane_vz11"
#define _LV_LETTER_L_		"Plane_vz12"
#define _LV_LETTER_M_		"Plane_vz13"
#define _LV_LETTER_N_		"Plane_vz14"
#define _LV_LETTER_O_		"Plane_vz15"
#define _LV_LETTER_P_		"Plane_vz16"
#define _LV_LETTER_Q_		"Plane_vz17"
#define _LV_LETTER_R_		"Plane_vz18"
#define _LV_LETTER_S_		"Plane_vz19"
#define _LV_LETTER_T_		"Plane_vz20"
#define _LV_LETTER_U_		"Plane_vz21"
#define _LV_LETTER_V_		"Plane_vz22"
#define _LV_LETTER_W_		"Plane_vz23"
#define _LV_LETTER_X_		"Plane_vz24"
#define _LV_LETTER_Y_		"Plane_vz25"
#define _LV_LETTER_Z_		"Plane_vz26"

#define _LV_LTANM_A_		"Plane_vz01Action.002"
#define _LV_LTANM_B_		"Plane_vz02Action.002"
#define _LV_LTANM_C_		"Plane_vz03Action.002"
#define _LV_LTANM_D_		"Plane_vz04Action.002"
#define _LV_LTANM_E_		"Plane_vz05Action.002"
#define _LV_LTANM_F_		"Plane_vz06Action.002"
#define _LV_LTANM_G_		"Plane_vz07Action.002"
#define _LV_LTANM_H_		"Plane_vz08Action.002"
#define _LV_LTANM_I_		"Plane_vz09Action.002"
#define _LV_LTANM_J_		"Plane_vz10Action.002"
#define _LV_LTANM_K_		"Plane_vz11Action.002"
#define _LV_LTANM_L_		"Plane_vz12Action.002"
#define _LV_LTANM_M_		"Plane_vz13Action.002"
#define _LV_LTANM_N_		"Plane_vz14Action.002"
#define _LV_LTANM_O_		"Plane_vz15Action.002"
#define _LV_LTANM_P_		"Plane_vz16Action.002"
#define _LV_LTANM_Q_		"Plane_vz17Action.002"
#define _LV_LTANM_R_		"Plane_vz18Action.002"
#define _LV_LTANM_S_		"Plane_vz19Action.002"
#define _LV_LTANM_T_		"Plane_vz20Action.002"
#define _LV_LTANM_U_		"Plane_vz21Action.002"
#define _LV_LTANM_V_		"Plane_vz22Action.002"
#define _LV_LTANM_W_		"Plane_vz23Action.002"
#define _LV_LTANM_X_		"Plane_vz24Action.002"
#define _LV_LTANM_Y_		"Plane_vz25Action.002"
#define _LV_LTANM_Z_		"Plane_vz26Action.002"

#define _LV_LT_TEXANM_A_	"Plane_vz01Action.001"
#define _LV_LT_TEXANM_B_ 	"Plane_vz02Action.001"
#define _LV_LT_TEXANM_C_ 	"Plane_vz03Action.001"
#define _LV_LT_TEXANM_D_ 	"Plane_vz04Action.001"
#define _LV_LT_TEXANM_E_ 	"Plane_vz05Action.001"
#define _LV_LT_TEXANM_F_	"Plane_vz06Action.001"
#define _LV_LT_TEXANM_G_	"Plane_vz07Action.001"
#define _LV_LT_TEXANM_H_ 	"Plane_vz08Action.001"
#define _LV_LT_TEXANM_I_   "Plane_vz09Action.001"
#define _LV_LT_TEXANM_J_	"Plane_vz10Action.001"
#define _LV_LT_TEXANM_K_	"Plane_vz11Action.001"
#define _LV_LT_TEXANM_L_	"Plane_vz12Action.001"
#define _LV_LT_TEXANM_M_	"Plane_vz13Action.001"
#define _LV_LT_TEXANM_N_	"Plane_vz14Action.001"
#define _LV_LT_TEXANM_O_	"Plane_vz15Action.001"
#define _LV_LT_TEXANM_P_	"Plane_vz16Action.001"
#define _LV_LT_TEXANM_Q_	"Plane_vz17Action.001"
#define _LV_LT_TEXANM_R_	"Plane_vz18Action.001"
#define _LV_LT_TEXANM_S_	"Plane_vz19Action.001"
#define _LV_LT_TEXANM_T_	"Plane_vz20Action.001"
#define _LV_LT_TEXANM_U_	"Plane_vz21Action.001"
#define _LV_LT_TEXANM_V_	"Plane_vz22Action.001"
#define _LV_LT_TEXANM_W_	"Plane_vz23Action.001"
#define _LV_LT_TEXANM_X_	"Plane_vz24Action.001"
#define _LV_LT_TEXANM_Y_	"Plane_vz25Action.001"
#define _LV_LT_TEXANM_Z_	"Plane_vz26Action.001"

#define _LVANM_ENTER_START_		580
#define _LVANM_ENTER_END_		610
#define _LVANM_EXIT_START_		700
#define _LVANM_EXIT_END_		715

const gkHashedString g_letters[] = 
{
	_LV_LETTER_A_,
	_LV_LETTER_B_,
	_LV_LETTER_C_,
	_LV_LETTER_D_,
	_LV_LETTER_E_,
	_LV_LETTER_F_,
	_LV_LETTER_G_,
	_LV_LETTER_H_,
	_LV_LETTER_I_,
	_LV_LETTER_J_,
	_LV_LETTER_K_,
	_LV_LETTER_L_,
	_LV_LETTER_M_,
	_LV_LETTER_N_,
	_LV_LETTER_O_,
	_LV_LETTER_P_,
	_LV_LETTER_Q_,
	_LV_LETTER_R_,
	_LV_LETTER_S_,
	_LV_LETTER_T_,
	_LV_LETTER_U_,
	_LV_LETTER_V_,
	_LV_LETTER_W_,
	_LV_LETTER_X_,
	_LV_LETTER_Y_,
	_LV_LETTER_Z_,	
};

const gkHashedString g_ltAnms[] = 
{
	_LV_LTANM_A_,
	_LV_LTANM_B_,
	_LV_LTANM_C_,
	_LV_LTANM_D_,
	_LV_LTANM_E_,
	_LV_LTANM_F_,
	_LV_LTANM_G_,
	_LV_LTANM_H_,
	_LV_LTANM_I_,
	_LV_LTANM_J_,
	_LV_LTANM_K_,
	_LV_LTANM_L_,
	_LV_LTANM_M_,
	_LV_LTANM_N_,
	_LV_LTANM_O_,
	_LV_LTANM_P_,
	_LV_LTANM_Q_,
	_LV_LTANM_R_,
	_LV_LTANM_S_,
	_LV_LTANM_T_,
	_LV_LTANM_U_,
	_LV_LTANM_V_,
	_LV_LTANM_W_,
	_LV_LTANM_X_,
	_LV_LTANM_Y_,
	_LV_LTANM_Z_,	
};


const gkHashedString g_lt_TexAnis[] = {
	_LV_LT_TEXANM_A_, 
	_LV_LT_TEXANM_B_,
	_LV_LT_TEXANM_C_,
	_LV_LT_TEXANM_D_,
	_LV_LT_TEXANM_E_,
	_LV_LT_TEXANM_F_,
	_LV_LT_TEXANM_G_,
	_LV_LT_TEXANM_H_,
	_LV_LT_TEXANM_I_,
	_LV_LT_TEXANM_J_,
	 _LV_LT_TEXANM_K_,
	_LV_LT_TEXANM_L_,
	_LV_LT_TEXANM_M_,
	_LV_LT_TEXANM_N_,
	_LV_LT_TEXANM_O_,
	_LV_LT_TEXANM_P_,
	_LV_LT_TEXANM_Q_,
	_LV_LT_TEXANM_R_,
	_LV_LT_TEXANM_S_,
	_LV_LT_TEXANM_T_,
	_LV_LT_TEXANM_U_,
	_LV_LT_TEXANM_V_,
	_LV_LT_TEXANM_W_,
	_LV_LT_TEXANM_X_,
	_LV_LT_TEXANM_Y_,
	_LV_LT_TEXANM_Z_,
};


LetterView::LetterView():RootView(false)
{
	m_ppViewNodeList = new ViewNode*[_LV_VN_NUM_];
	m_ppAnmList = new BlenderAnimation*[_LV_VN_NUM_];
	m_ppTexAnmList = new BlenderAnimation*[_LV_VN_NUM_];
	for (int i = 0;i<_LV_VN_NUM_;i++)
	{
		m_ppViewNodeList[i] = (new ViewNode(Aabridge::getScene(),g_letters[i]))->setIndex(i,i);
		m_ppAnmList[i] = new BlenderAnimation(Aabridge::getScene(),m_ppViewNodeList[i]->getGameObj(),g_ltAnms[i]);
		m_ppTexAnmList[i] = new BlenderAnimation(Aabridge::getScene(), m_ppViewNodeList[i]->getGameObj(),g_lt_TexAnis[i]);
	}
	setViewNodeNum(_LV_VN_NUM_);
	setViewNodeList(m_ppViewNodeList);
}

LetterView::~LetterView() 
{
	m_ppViewNodeList = NULL;

	ui_deleteArray(m_ppAnmList,_LV_VN_NUM_);
}
//
//char 
//LetterView::getHitLetter()				// return NULL or ‘#’ or ‘A’~‘Z’
//{
//	for (int i = 1;i<_LV_VN_NUM_;i++)
//	{
//		if(m_ppViewNodeList[i]->getGameObj()->isMouseClickNow())
//			return i-1+'A';
//	}
//
//	return NULL;
//}
//
//char 
//LetterView::getCurrentLetter()			// 获取当前焦点所在的字母
//{
//	ViewNode* pFocus = getFocus();
//	for (int i = 1;i<_LV_VN_NUM_;i++)
//	{
//		if(m_ppViewNodeList[i] == pFocus)
//			return i-1+'A';
//	}
//	return NULL;
//}
//
//char 
//LetterView::viewNodeToChar(ViewNode* pNode)
//{
//
//}

void 
LetterView::loseViewFocus()
{
	
}

void 
LetterView::showView()
{
	for (int i = 0;i<_LV_VN_NUM_;i++)
	{
		m_ppAnmList[i]->setFrameScope(_LVANM_ENTER_START_,_LVANM_ENTER_END_);
		m_ppAnmList[i]->play();

		m_ppTexAnmList[i]->setFrameScope(_LVANM_ENTER_START_,_LVANM_ENTER_END_);
		m_ppTexAnmList[i]->play();
	}
}

void 
LetterView::hideView()
{
	for (int i = 0;i<_LV_VN_NUM_;i++)
	{
		m_ppAnmList[i]->setFrameScope(_LVANM_EXIT_START_,_LVANM_EXIT_END_);
		m_ppAnmList[i]->play();

		m_ppTexAnmList[i]->setFrameScope(_LVANM_EXIT_START_,_LVANM_EXIT_END_);
		m_ppTexAnmList[i]->play();
	}
}
