//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//

#if !defined(_MENU_H)
#define _MENU_H

#include <gkScene.h>
#include "BlenderAnimation.h"
#include "RootView.h"
#include "BlenderAnmInterface.h"

class ViewNode;
class Menu:public RootView,public BlenderAnmInterface
{
public:
	Menu(gkScene*);
	~Menu();

	void setMenuVisible(bool b);
	bool getMenuVisible();
	bool isHitHomeEdit(Ogre::RaySceneQueryResult& hitList);
	bool isHitWallpaperSetting(Ogre::RaySceneQueryResult& hitList);
	bool isFocusOnHomeEdit();
	bool isFocusOnWallpaper();
	bool MoveFocus(eFlyDirection eDir);

	virtual void loseViewFocus(){};
	virtual bool setFocus(ViewNode* node,bool isCircle = true);
	virtual bool setFocus(int index,bool isCircle = true);
	virtual void onBlenderAnmFinish(BlenderAnimation* p,int s,int e);
private:
	inline void showMenu();
	inline void hideMenu();
	inline void setTimePosition(int start,int end);
private:
	bool m_bMenuVisible;
	gkScene* m_pScene;
	//gkGameObject* m_pMenuNode;		// menu 根节点
	//gkGameObject* m_pHomeEditNode;	// 桌面编辑node
	//gkGameObject* m_pWallpaperNode; // 纸墙设定node
	ViewNode** m_ppViewNodeList;
	BlenderAnimation** m_ppBldAnm;
};
#endif // _MENU_H
