//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MenuView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "MenuView.h"
#include "ViewNode.h"
#include "Aabridge.h"
#include "BlenderAnimation.h"

#define _AAMENU_NODE_NAME_		"Plane_x06b"
#define _AAMENU_HOMEAPP_NAME_	"Plane_yc01"
#define _AAMENU_UNINSTALL_NAME_ "Plane_yd01"
#define _AAMENU_ANM0_NAME_		"Plane_x06Action.001"
#define _AAMENU_ANM1_NAME_		"Plane_yc01Action"


#define _AAMENU_SHOW_ANM_START_		660
#define _AAMENU_SHOW_ANM_END_		680
#define _AAMENU_HIDE_ANM_START_		680
#define _AAMENU_HIDE_ANM_END_		700

MenuView::MenuView():m_visible(false),m_pScene(NULL),m_ppNodeList(NULL)
{
	m_pScene = Aabridge::getScene();

	if (m_pScene)
	{
		m_ppNodeList = getViewNodeList();
		m_ppNodeList = new ViewNode*[2];
		m_ppNodeList[0] = (new ViewNode(m_pScene,_AAMENU_HOMEAPP_NAME_))->setIndex(0,0);
		m_ppNodeList[1] = (new ViewNode(m_pScene,_AAMENU_UNINSTALL_NAME_))->setIndex(1,1);
		m_ppNodeList[0]->getGameObj()->setObjectRenderPriority(80);
		m_ppNodeList[1]->getGameObj()->setObjectRenderPriority(80);
		m_pScene->getObject("Plane_y00b")->setObjectRenderPriority(80);
		setViewNodeNum(2);
		setViewNodeList(m_ppNodeList);

		m_pMenuNode = m_pScene->getObject(_AAMENU_NODE_NAME_);
		m_pBldAnm = new BlenderAnimation(m_pScene,m_pMenuNode,_AAMENU_ANM0_NAME_);
		m_pBldAnm1 = new BlenderAnimation(m_pScene,m_ppNodeList[0]->getGameObj(),_AAMENU_ANM1_NAME_);
	}
}

MenuView::~MenuView() 
{
	ui_delete(m_pBldAnm);
	ui_delete(m_pBldAnm1);
}

void 
MenuView::setVisible(bool visible)
{
	if(m_visible == visible)
		return;
	m_visible = visible;
	m_visible?showMenu():hideMenu();
}

bool 
MenuView::getVisible()
{
	return m_visible;
}

bool 
MenuView::isHitSetHomeApps(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppNodeList[0]->getGameObj());
}

bool 
MenuView::isHitUninstallApps(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppNodeList[1]->getGameObj());
}

int 
MenuView::getSetHomeNodeIndex()
{
	return getViewNodeList()[0]->getMinIndex();
}

int 
MenuView::getUninstallNodeIndex()
{
	return getViewNodeList()[1]->getMinIndex();
}

void 
MenuView::showMenu()
{
	setTimePosition(_AAMENU_SHOW_ANM_START_,_AAMENU_SHOW_ANM_END_);
	m_pBldAnm->play();
	m_pBldAnm1->play();
}

void 
MenuView::hideMenu()
{
	setTimePosition(_AAMENU_HIDE_ANM_START_,_AAMENU_HIDE_ANM_END_);
	m_pBldAnm->play();
	m_pBldAnm1->play();
}

void 
MenuView::setTimePosition(int start,int end)
{
	m_pBldAnm->setFrameScope(start,end);
	m_pBldAnm1->setFrameScope(start,end);
	
}

void 
MenuView::loseViewFocus()
{
	setVisible(false);
}
