//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MenuView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "MenuViewImpl.h"
#include "MenuView.h"
#include "Aabridge.h"
#include "ViewNode.h"

MenuViewImpl::MenuViewImpl() 
{
	m_pMenuView = new MenuView();
	setRootView(m_pMenuView);
}

MenuViewImpl::~MenuViewImpl() 
{
	ui_delete(m_pMenuView);
}

void 
MenuViewImpl::setMenuVisible(bool v)
{
	m_pMenuView->setVisible(v);
}

bool 
MenuViewImpl::getMenuVisible()
{
	return m_pMenuView->getVisible();
}

bool 
MenuViewImpl::isHitSetHomeApps()
{
	return false;
}

bool 
MenuViewImpl::isHitUninstallApps()
{
	return false;
}

void 
MenuViewImpl::onHitSetHomeApps()
{
	setMenuVisible(false);
	//Aabridge::getInstance()->getIntoHASettings();
}

void 
MenuViewImpl::onHitUninstallApps()
{
	setMenuVisible(false);
//	Aabridge::getInstance()->setUninstallAppMode();
}

bool 
MenuViewImpl::moveFocus(eFlyDirection direct)	// 移动focus
{
	return true;//m_pMenuView->moveFocus(direct);
}

bool 
MenuViewImpl::MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction)
{
	return true;
}

bool 
MenuViewImpl::setViewNodeFocus(ViewNode* pNode)	// 设置viewNode* 为当前focus
{
	return m_pMenuView->setFocus(pNode);
}

ViewNode* 
MenuViewImpl::getCurrentViewNode()
{
	return m_pMenuView->getFocus();
}

void 
MenuViewImpl::onLoseFocus()
{

}

void 
MenuViewImpl::onClickViewNode(ViewNode* pNode)
{
	int index = pNode->getMinIndex();

	if (index == m_pMenuView->getSetHomeNodeIndex())
	{
		onHitSetHomeApps();
	}
	else if (index == m_pMenuView->getUninstallNodeIndex())
	{
		onHitUninstallApps();
	}
}

void 
MenuViewImpl::onHitCurrentNode()			// 
{
	onClickViewNode(m_pMenuView->getFocus());
}
