//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.cpp
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#include "Movieinfo_Block.h"

#define _MI_BLOCK_PARENT_	"Plane_x03"
#define _MI_BLOCK_PARENTMK_	"Plane_x03c"
#define _MI_BLOCK_PLANE0_	"Plane_ca01"	// 畅游应用
#define _MI_BLOCK_PLANE1_	"Plane_ca02"	// 应用商店
#define _MI_BLOCK_PLANE2_	"Plane_ca03"	// 所有应用
#define _MI_BLOCK_PLANE3_	"Plane_ca04"	// TV icon
#define _MI_BLOCK_PLANE4_	"Plane_ca05"	// 影视资料
#define _MI_BLOCK_PLANE5_	"Plane_cb01"	// 宿醉2
#define _MI_BLOCK_PLANE6_	"Plane_cb02"	// 朱诺
#define _MI_BLOCK_PLANE7_	"Plane_cb03"	// 疯狂出租车
#define _MI_BLOCK_PLANE8_	"Plane_cb04"	// 劈腿绯闻
#define _MI_BLOCK_PLANE9_	"Plane_cb05"	// grab life
#define _MI_BLOCK_PLANE10_	"Plane_cb06"	// meet the parents
#define _MI_BLOCK_PLANE11_	"Plane_cb07"	// 警察故事
#define _MI_BLOCK_PLANE12_	"Plane_cb08"	// 超速绯闻
#define _MI_BLOCK_PLANE13_	"Plane_cb09"	// 更多
#define _MI_BLOCK_ANM_NAME_	"Plane_x03Action"
#define _MI_BLOCK_PLANENUM_	11	

#define _MI_BLOCK_EDITMENU_ITEM_	1
#define _MI_BLICK_ITEM0_			"Plane_x03b1"
#define _MI_BLICK_ITEM0_ANM0_		"Plane_xa01Action.002"
#define _MI_BLICK_ITEM0_ANM1_		"Plane_xa01Action.001"
#define _MI_BLICK_ITEM0_ANM2_		"Plane_xa01bAction.002"

MovieinfoBlock::MovieinfoBlock(gkScene* pscene):Block(pscene) 
{
	if (m_pScene)
	{
		m_ppShortcutList = new AppUnitShortcut*[_MI_BLOCK_PLANENUM_];
		m_ppShortcutList[0] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE0_));
// 		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE1_))->setIndex(-6,-6);
// 		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE2_))->setIndex(-5,-5);
// 		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE3_))->setIndex(-4,-4);
		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE4_))->setIndex(-3,-1);
		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE5_))->setIndex(0,4);
		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE6_))->setIndex(2,2);
		m_ppShortcutList[4] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE7_))->setIndex(5,5);
		m_ppShortcutList[5] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE8_))->setIndex(6,6);
		m_ppShortcutList[6] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE9_))->setIndex(7,7);
		m_ppShortcutList[7] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE10_))->setIndex(8,8);
		m_ppShortcutList[8] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE11_))->setIndex(9,9);
		m_ppShortcutList[9] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE12_))->setIndex(10,10);
		m_ppShortcutList[10] = (new AppUnitShortcut(m_pScene,_MI_BLOCK_PLANE13_))->setIndex(11,11);

		m_ShortCutNum = _MI_BLOCK_PLANENUM_;

		m_BlockParentPlane = m_pScene->getObject(_MI_BLOCK_PARENT_);
		m_BlockParentPlane->setVisible(false);
		m_pBldAnm = new BlenderAnimation(m_pScene,m_BlockParentPlane,_MI_BLOCK_ANM_NAME_);
		m_pMaskPlane = m_pScene->getObject(_MI_BLOCK_PARENTMK_);
		m_pMaskPlane->setVisible(false);
#if !_LAUNCHER_EDITMENU_OLDSTYLE_
		initEditMenu();
#endif
	}

}

MovieinfoBlock::~MovieinfoBlock() 
{
	ui_deleteArray(m_ppMenuAnmList,_BLOCK_EDITMENU_ANM_*_MI_BLOCK_EDITMENU_ITEM_);
}

BlockEnum
MovieinfoBlock::getBlockEnum()
{
	return Movie_Block;
}

int 
MovieinfoBlock::getMenuFlag()
{
	return 1;
}

int 
MovieinfoBlock::getVacantPosParentID()
{
	return 3;
}
void 
MovieinfoBlock::initEditMenu()
{
	m_MenuItemNum = _MI_BLOCK_EDITMENU_ITEM_;
	m_MenuItemFocus = 0;

	m_ppMenuAnmList = new BlenderAnimation*[_BLOCK_EDITMENU_ANM_*_MI_BLOCK_EDITMENU_ITEM_];
	m_ppMenuAnmList[0] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MI_BLICK_ITEM0_),_MI_BLICK_ITEM0_ANM0_);
	m_ppMenuAnmList[1] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MI_BLICK_ITEM0_),_MI_BLICK_ITEM0_ANM1_);
	m_ppMenuAnmList[2] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MI_BLICK_ITEM0_),_MI_BLICK_ITEM0_ANM2_);
	m_ppMenuAnmList[0]->setAnmInterface(this);

	m_ppMenuObjList = new gkGameObject*[_MI_BLOCK_EDITMENU_ITEM_];
	m_ppMenuObjList[0] = m_pScene->getObject(_MI_BLICK_ITEM0_);
	m_ppMenuObjList[0]->setVisible(false);

}
