//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Recommand Block.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_MOVIEINFO_BLOCK_H)
#define _MOVIEINFO_BLOCK_H

#include "Block.h"

class MovieinfoBlock :public Block
{
public:
	MovieinfoBlock(gkScene*);
	~MovieinfoBlock();
	virtual BlockEnum getBlockEnum(); 
	virtual int getMenuFlag();
	virtual int getVacantPosParentID();
protected:
	virtual void initEditMenu();
};

#endif  //_MOVIEINFO_BLOCK_H
