//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Recommand Block.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_MY_BLOCK_H)
#define _MY_BLOCK_H

#include "Block.h"

class MyBlock :public Block
{
public:
	MyBlock(gkScene*);
	~MyBlock();
	virtual BlockEnum getBlockEnum(); 
	virtual int getMenuFlag();
	virtual int getVacantPosParentID();
	virtual bool isDelete();
	virtual void addMyBlock();
	virtual void deleteMyBlock();
	virtual bool setMyBlockFocusVisible(bool isVisible);
	virtual gkGameObject * getAddBlockSymbol();
protected:
	void setBlockVisible(bool isBlockVisable); 
	virtual void initEditMenu();
private:
	bool mIsDelete;
	gkGameObject * m_addBlockSymbol;
	gkGameObject * m_addBlockFocus;
};

#endif  //_MY_BLOCK_H
