//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.cpp
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#include "My_Block.h"
#include "gkEntity.h"

#ifdef _LAUNCHER_EDITMENU_OLDSTYLE_
#define _MY_BLOCK_PARENT_	"Plane_x05xa"
#else
#define _MY_BLOCK_PARENT_	"Plane_x05xa"
#endif

#define _MY_BLOCK_PARENTMK_	"Plane_x05xc"
#define _MY_BLOCK_PLANE0_	"Plane_fa05"	// Ï²°®Ó¦ÓÃ
#define _MY_BLOCK_PLANE1_	"Plane_fb01"	// çÍ·×ÀàÈÝ
#define _MY_BLOCK_PLANE2_	"Plane_fb02"	// 
#define _MY_BLOCK_PLANE3_	"Plane_fb03"	// 
#define _MY_BLOCK_PLANE4_	"Plane_fb04"	// 
#define _MY_BLOCK_PLANE5_	"Plane_fb05"	// 
#define _MY_BLOCK_PLANE6_	"Plane_fb06"	// 
#define _MY_BLOCK_PLANE7_	"Plane_fb07"	// 
#define _MY_BLOCK_PLANE8_	"Plane_fb08"	// 
#define _MY_BLOCK_PLANE9_	"Plane_fb09"	// 
#define _MY_BLOCK_PLANE10_	"Plane_fb10"	// 
#define _MY_BLOCK_PLANE11_	"Plane_fb11"	// 
#define _MY_BLOCK_PLANE12_	"Plane_fb12"	// 
#define _MY_BLOCK_PLANENUM_	 12	// 
#define _MY_BLOCK_ANM_NAME_ "Plane_x04Action.001"

#define _MY_BLOCK_EDITMENU_ITEM_ 3
#define _MY_BLICK_ITEM0_		"Plane_x05xb1"
#define _MY_BLICK_ITEM0_ANM0_	"Plane_xa01Action.005"
#define _MY_BLICK_ITEM0_ANM1_	"Plane_xa01Action.001"
#define _MY_BLICK_ITEM0_ANM2_	"Plane_xa01bAction.002"
#define _MY_BLICK_ITEM1_		"Plane_x05xb2"
#define _MY_BLICK_ITEM1_ANM0_	"Plane_xa02Action.005"
#define _MY_BLICK_ITEM1_ANM1_	"Plane_xa02Action.001"
#define _MY_BLICK_ITEM1_ANM2_	"Plane_xa02bAction"
#define _MY_BLICK_ITEM2_		"Plane_x05xb3"
#define _MY_BLICK_ITEM2_ANM0_	"Plane_xa03Action.005"
#define _MY_BLICK_ITEM2_ANM1_	"Plane_xa03Action.001"
#define _MY_BLICK_ITEM2_ANM2_	"Plane_xa03bAction"

#define  _MY_BLOCK_ADD_SYSBOL "Plane_fbz13z"
#define  _MY_BLOCK_ADD_FOCUS "AddFocus"
MyBlock::MyBlock(gkScene* pscene):Block(pscene),mIsDelete(false) 
{
	if (m_pScene)
	{
		m_ppShortcutList = new AppUnitShortcut*[_MY_BLOCK_PLANENUM_];
		m_ppShortcutList[0] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE1_))->setIndex(0,0);
		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE2_))->setIndex(1,1);
		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE3_))->setIndex(2,2);
		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE4_))->setIndex(3,3);
		m_ppShortcutList[4] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE5_))->setIndex(4,4);
		m_ppShortcutList[5] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE6_))->setIndex(5,5);
		m_ppShortcutList[6] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE7_))->setIndex(6,6);
		m_ppShortcutList[7] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE8_))->setIndex(7,7);
		m_ppShortcutList[8] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE9_))->setIndex(8,8);
		m_ppShortcutList[9] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE10_))->setIndex(9,9);
		m_ppShortcutList[10] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE11_))->setIndex(10,10);
		m_ppShortcutList[11] = (new AppUnitShortcut(m_pScene,_MY_BLOCK_PLANE12_))->setIndex(11,11);

		m_ShortCutNum = _MY_BLOCK_PLANENUM_;
		m_BlockParentPlane = m_pScene->getObject(_MY_BLOCK_PARENT_);
		m_BlockParentPlane->setVisible(false);
		m_pBldAnm = new BlenderAnimation(m_pScene,m_BlockParentPlane,_MY_BLOCK_ANM_NAME_);
		m_pMaskPlane = m_pScene->getObject(_MY_BLOCK_PARENTMK_);
		m_pMaskPlane->setVisible(false);
		setXVisible(false);
#if !_LAUNCHER_EDITMENU_OLDSTYLE_
		initEditMenu();
#endif
	}
}
MyBlock::~MyBlock() 
{
	ui_deleteArray(m_ppMenuAnmList,_BLOCK_EDITMENU_ANM_*_MY_BLOCK_EDITMENU_ITEM_);
}

int 
MyBlock::getMenuFlag()
{
	return 1<<2|1<<1|1;
}

int 
MyBlock::getVacantPosParentID()
{
	return 6;
}

void 
MyBlock::initEditMenu()
{
	m_MenuItemNum = _MY_BLOCK_EDITMENU_ITEM_;
	m_MenuItemFocus = 0;

	m_ppMenuAnmList = new BlenderAnimation*[_BLOCK_EDITMENU_ANM_*_MY_BLOCK_EDITMENU_ITEM_];
	m_ppMenuAnmList[0] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM0_),_MY_BLICK_ITEM0_ANM0_);
	m_ppMenuAnmList[1] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM0_),_MY_BLICK_ITEM0_ANM1_);
	m_ppMenuAnmList[2] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM0_),_MY_BLICK_ITEM0_ANM2_);
	m_ppMenuAnmList[3] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM1_),_MY_BLICK_ITEM1_ANM0_);
	m_ppMenuAnmList[4] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM1_),_MY_BLICK_ITEM1_ANM1_);
	m_ppMenuAnmList[5] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM1_),_MY_BLICK_ITEM1_ANM2_);
	m_ppMenuAnmList[6] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM2_),_MY_BLICK_ITEM2_ANM0_);
	m_ppMenuAnmList[7] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM2_),_MY_BLICK_ITEM2_ANM1_);
	m_ppMenuAnmList[8] = new BlenderAnimation(m_pScene,m_pScene->getObject(_MY_BLICK_ITEM2_),_MY_BLICK_ITEM2_ANM2_);

	m_ppMenuAnmList[0]->setAnmInterface(this);

	m_ppMenuObjList = new gkGameObject*[_MY_BLOCK_EDITMENU_ITEM_];
	m_ppMenuObjList[0] = m_pScene->getObject(_MY_BLICK_ITEM0_);
	m_ppMenuObjList[1] = m_pScene->getObject(_MY_BLICK_ITEM1_);
	m_ppMenuObjList[2] = m_pScene->getObject(_MY_BLICK_ITEM2_);
	m_ppMenuObjList[0]->setVisible(false);
	m_ppMenuObjList[1]->setVisible(false);
	m_ppMenuObjList[2]->setVisible(false);

	m_addBlockSymbol = m_pScene->getObject(_MY_BLOCK_ADD_SYSBOL);
	m_addBlockSymbol->setVisible(false);

	m_addBlockFocus = m_pScene->getObject(_MY_BLOCK_ADD_FOCUS);
	m_addBlockFocus->setVisible(false);
// 	float scalex = m_addBlockFocus->getScale().x > 1 ? m_addBlockFocus->getScale().x: 1;
// 	float scaley = m_addBlockFocus->getScale().y > 1 ? m_addBlockFocus->getScale().y: 1;
// 	Ogre::Vector4 texM = Ogre::Vector4(scalex,scaley,0,0);
// 	((gkEntity*)m_addBlockFocus)->setTextureMatrix(0,texM,0);
// 	((gkEntity*)m_addBlockFocus)->setTextureMatrix(0,texM,1);
}

bool
MyBlock::isDelete()
{
	return mIsDelete;
}

void 
MyBlock::addMyBlock()
{
	if (mIsDelete)
	{
		setBlockVisible(true);
		setMyBlockFocusVisible(false);
		mIsDelete = false;
	}
}

void
MyBlock::deleteMyBlock()
{
	setBlockVisible(false);
	mIsDelete = true;
}


void 
MyBlock::setBlockVisible(bool isBlockVisable)
{
	//m_addBlockFocus->setVisible(!isBlockVisable);
	m_addBlockSymbol->setVisible(!isBlockVisable);
	for (int i = 0; i < _MY_BLOCK_PLANENUM_; i++)
	{
		m_ppShortcutList[i]->getGameObj()->setVisible(isBlockVisable);
	}
	for (int i = 0; i < _MY_BLOCK_EDITMENU_ITEM_; i++)
	{
		m_ppMenuObjList[i]->setVisible(isBlockVisable);
	}
	Block::setBlockVisible(isBlockVisable);
}

 bool 
MyBlock::setMyBlockFocusVisible(bool isVisible)
 {
	m_addBlockFocus->setVisible(isVisible);
	return true;
 }

gkGameObject * 
MyBlock::getAddBlockSymbol()
 {
	 return m_addBlockSymbol;
 }

BlockEnum
MyBlock::getBlockEnum()
{
	return My_Block;
}