//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.cpp
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#include "Recommend_Block.h"

#define _RC_BLOCK_PARENT_	"Plane_x02"
#define _RC_BLOCK_PARENTMK_	"Plane_x02c"
#define _RC_BLOCK_PLANE4_	"Plane_ba05"	// 推荐应用
#define _RC_BLOCK_PLANE5_	"Plane_bb01"	// 全部应用
#define _RC_BLOCK_PLANE6_	"Plane_bb02"	// 附件商城
#define _RC_BLOCK_PLANE7_	"Plane_bb03"	// 帮助
#define _RC_BLOCK_PLANE8_	"Plane_bb04"	// 多屏互动
#define _RC_BLOCK_PLANE9_	"Plane_bb05"	// 应用商城
#define _RC_BLOCK_PLANE10_	"Plane_bb06"	// 浏览器
#define _RC_BLOCK_PLANE11_	"Plane_bb07"	// 浏览器
#define _RC_BLOCK_PLANE12_	"Plane_bb08"	// 云裳音乐
#define _RC_BLOCK_PLANE13_	"Plane_bb09"	// 我是凡客
#define _RC_BLOCK_PLANENUM_	10
#define _RC_BLOCK_ANM_NAME_ "Plane_x02Action"

#define _RC_BLOCK_PLANE14_ "Plane_x02b1"
#define _RC_BLOCK_EMANM0_	"Plane_xa01Action"
#define _RC_BLOCK_EMANM1_	"Plane_xa01Action.001"
#define _RC_BLOCK_EMANM2_	"Plane_xa01bAction"
#define _RC_BLOCK_EDITMENU_ITEM_	1

RecommendBlock::RecommendBlock(gkScene* pscene):Block(pscene)
{
	if (m_pScene)
	{
		m_BlockParentPlane = m_pScene->getObject(_RC_BLOCK_PARENT_);

		m_ppShortcutList = new AppUnitShortcut*[_RC_BLOCK_PLANENUM_];
		m_ppShortcutList[0] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE4_))->setIndex(-3,-1);
		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE5_))->setIndex(0,1);
		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE6_))->setIndex(2,2);
		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE7_))->setIndex(3,3);
		m_ppShortcutList[4] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE8_))->setIndex(4,4);
		m_ppShortcutList[5] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE9_))->setIndex(5,5);
		m_ppShortcutList[6] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE10_))->setIndex(6,6);
		m_ppShortcutList[7] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE11_))->setIndex(7,7);
		m_ppShortcutList[8] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE12_))->setIndex(8,8);
		m_ppShortcutList[9] = (new AppUnitShortcut(m_pScene,_RC_BLOCK_PLANE13_))->setIndex(9,11);

		//m_ppShortcutList = temp;
		m_ShortCutNum = _RC_BLOCK_PLANENUM_;

		m_pCurrentFocus = m_ppShortcutList[3];
		
		m_BlockParentPlane->setVisible(false);
		m_pBldAnm = new BlenderAnimation(m_pScene,m_BlockParentPlane,_RC_BLOCK_ANM_NAME_);
		m_pMaskPlane = m_pScene->getObject(_RC_BLOCK_PARENTMK_);
		m_pMaskPlane->setVisible(false);
#if !_LAUNCHER_EDITMENU_OLDSTYLE_
		initEditMenu();
#endif
	}
}
RecommendBlock::~RecommendBlock() 
{
	ui_deleteArray(m_ppMenuAnmList,_BLOCK_EDITMENU_ANM_*_RC_BLOCK_EDITMENU_ITEM_);
}

BlockEnum
RecommendBlock::getBlockEnum()
{
	return Recommend_Block;
}

int 
RecommendBlock::getMenuFlag()
{
	return 1;
}

int 
RecommendBlock::getVacantPosParentID()
{
	return 2;
}

void 
RecommendBlock::initEditMenu()
{
	m_MenuItemNum = _RC_BLOCK_EDITMENU_ITEM_;
	m_MenuItemFocus = 0;

	m_ppMenuAnmList = new BlenderAnimation*[_BLOCK_EDITMENU_ANM_*_RC_BLOCK_EDITMENU_ITEM_];
	m_ppMenuAnmList[0] = new BlenderAnimation(m_pScene,m_pScene->getObject(_RC_BLOCK_PLANE14_),_RC_BLOCK_EMANM0_);
	m_ppMenuAnmList[1] = new BlenderAnimation(m_pScene,m_pScene->getObject(_RC_BLOCK_PLANE14_),_RC_BLOCK_EMANM1_);
	m_ppMenuAnmList[2] = new BlenderAnimation(m_pScene,m_pScene->getObject(_RC_BLOCK_PLANE14_),_RC_BLOCK_EMANM2_);
	m_ppMenuAnmList[0]->setAnmInterface(this);

	m_ppMenuObjList = new gkGameObject*[_RC_BLOCK_EDITMENU_ITEM_];
	m_ppMenuObjList[0] = m_pScene->getObject(_RC_BLOCK_PLANE14_);
	m_ppMenuObjList[0]->setVisible(false);

}
