//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Recommand Block.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_RECOMMAND_BLOCK_H)
#define _RECOMMAND_BLOCK_H

#include "Block.h"

class RecommendBlock :public Block
{
public:
	RecommendBlock(gkScene*);
	~RecommendBlock();
	virtual BlockEnum getBlockEnum();
	virtual int getMenuFlag();
	virtual int getVacantPosParentID();
	//virtual void setMenuItemFoucsIndex(int index);
protected:
	virtual void initEditMenu();

};

#endif  //_RECOMMAND_BLOCK_H
