//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RootViewImpl.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "RootViewImpl.h"
#include "Rootview.h"

#define _DERICTION_NUM_		4
RootViewImpl::RootViewImpl():m_pRootView(NULL)
{	
	m_NextFocusViewImpl = new RootViewImpl*[_DERICTION_NUM_];
	for (int i = 0;i<_DERICTION_NUM_;i++)
	{
		m_NextFocusViewImpl[i] = NULL;
	}
}

RootViewImpl::~RootViewImpl()
{
	delete[] m_NextFocusViewImpl;
}

void 
RootViewImpl::onTick(gkScalar time)
{
	RootView::onTick(time);
}

void 
RootViewImpl::setRootView(RootView* pView)
{
	m_pRootView = pView;
}

ViewNode* 
RootViewImpl::getHitViewNode(Ogre::RaySceneQueryResult& objArray)
{
	return m_pRootView?m_pRootView->isHitViewNode(objArray):NULL;
}

RootView* 
RootViewImpl::getRootView()
{
	return m_pRootView;
}

void 
RootViewImpl::setViewVisible(bool vsb)
{
	if(m_pRootView)
		m_pRootView->setVisible(vsb);
}

bool 
RootViewImpl::getViewVisible()
{
	if(getRootView())
		return getRootView()->getVisible();
	return true;
}

void 
RootViewImpl::setFocusViewImpl(RootViewImpl* pLeftVi,RootViewImpl* pRightVi,RootViewImpl* pUpVi,RootViewImpl* pDownVi)
{
	m_NextFocusViewImpl[LEFT] = pLeftVi;
	m_NextFocusViewImpl[RIGHT] = pRightVi;
	m_NextFocusViewImpl[UP] = pUpVi;
	m_NextFocusViewImpl[DOWN] = pDownVi;
}

void 
RootViewImpl::setLeftViewImpl(RootViewImpl* pViewImpl)
{
	m_NextFocusViewImpl[LEFT] = pViewImpl;
}

void 
RootViewImpl::setRightViewImpl(RootViewImpl* pViewImpl)
{
	m_NextFocusViewImpl[RIGHT] = pViewImpl;
}

void 
RootViewImpl::setUpViewImpl(RootViewImpl* pViewImpl)
{
	m_NextFocusViewImpl[UP] = pViewImpl;
}

void 
RootViewImpl::setDownViewImpl(RootViewImpl* pViewImpl)
{
	m_NextFocusViewImpl[DOWN] = pViewImpl;
}

RootViewImpl** 
RootViewImpl::getFocusViewImpl()
{
	return m_NextFocusViewImpl;
}

RootViewImpl* 
RootViewImpl::getFocusViewImpl(eFlyDirection direct)
{
	return m_NextFocusViewImpl[direct];
}

RootViewImpl* 
RootViewImpl::getLeftViewImpl()
{
	return m_NextFocusViewImpl[LEFT];
}

RootViewImpl* 
RootViewImpl::getRightViewImpl()
{
	return m_NextFocusViewImpl[RIGHT];
}

RootViewImpl* 
RootViewImpl::getUpViewImpl()
{
	return m_NextFocusViewImpl[UP];
}

RootViewImpl* 
RootViewImpl::getDownViewImpl()
{
	return m_NextFocusViewImpl[DOWN];
}