//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ScrollbarView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//

#include "Aabridge.h"
#include "ScrollbarView.h"
#include "ViewNode.h"
#include "BlenderAnimation.h"
#include "ScrollViewImpl.h"

#define _SB_VN_NUM_	2

//a18�汾֮ǰ
// #define _SB_SB_NAME_		"Plane_vzza0"
 #define _SB_SB_NAME_		"Plane_vzza2"
 #define _SB_SBTRACK_NAME_	"Plane_vzza1"
 
 #define _SB_SB_ANM_			"Plane_vzza2Action"
 #define _SB_SBTRACK_ANM_	"Plane_vzza1Action"

#define _SB_SB_TEX_ANI_        "Plane_vzza2Action.001"
#define _SB_SBTRACK_TEX_ANI_  "Plane_vzza1Action.001"

#define _SBANM_ENTER_START_	590
#define _SBANM_ENTER_END_	610
#define _SBANM_EXIT_START_	700
#define _SBANM_EXIT_END_	715

ScrollbarView::ScrollbarView():RootView(false),m_ppViewNode(NULL)
{
	setViewNodeNum(_SB_VN_NUM_);
	m_ppViewNode = getViewNodeList();
	m_ppViewNode = new ViewNode*[_SB_VN_NUM_];
	m_ppBldAnm = new BlenderAnimation*[_SB_VN_NUM_];
	m_ppBldTexAnm = new BlenderAnimation*[_SB_VN_NUM_];

	m_ppViewNode[0] = new ViewNode(Aabridge::getScene(),_SB_SB_NAME_);
	m_ppViewNode[1] = new ViewNode(Aabridge::getScene(),_SB_SBTRACK_NAME_);

	m_ppBldAnm[0] = new BlenderAnimation(Aabridge::getScene(),m_ppViewNode[0]->getGameObj(),_SB_SB_ANM_,this);
	m_ppBldAnm[1] = new BlenderAnimation(Aabridge::getScene(),m_ppViewNode[1]->getGameObj(),_SB_SBTRACK_ANM_,this);

	m_ppBldTexAnm[0] = new BlenderAnimation(Aabridge::getScene(), m_ppViewNode[0]->getGameObj(), _SB_SB_TEX_ANI_,this);
	m_ppBldTexAnm[1] = new BlenderAnimation(Aabridge::getScene(), m_ppViewNode[1]->getGameObj(), _SB_SBTRACK_TEX_ANI_);

	setViewNodeList(m_ppViewNode);
	//m_SBRawPos = m_ppViewNode[0]->getGameObj()->getPosition();
	//m_SBCurPos = m_SBRawPos;
}

ScrollbarView::~ScrollbarView() 
{
	m_ppViewNode = NULL;
	ui_deleteArray(m_ppBldAnm,_SB_VN_NUM_);
	ui_deleteArray(m_ppBldTexAnm,_SB_VN_NUM_);
}

void 
ScrollbarView::loseViewFocus()
{
}

bool 
ScrollbarView::setFocus(ViewNode* node)
{
	RootView::setFocus(m_ppViewNode[0]);
	return true;
}

void 
ScrollbarView::setScrollBarScale(gkVector3 gScale)
{
	m_ppViewNode[0]->getGameObj()->setScale(gScale);
}

void 
ScrollbarView::setScrollBarPosition(gkVector3 gPosition)
{
	m_ppViewNode[0]->getGameObj()->setPosition(gPosition);
	m_SBCurPos = gPosition;
}

// void 
// ScrollbarView::setSBRawPosition(gkVector3 rawpos)
// {
// 	m_SBRawPos = rawpos;
// 	m_SBCurPos = m_SBRawPos;
// }

// gkVector3 
// ScrollbarView::getSBRawPosition()
// {
// 	return m_SBRawPos;
// }

gkVector3 
ScrollbarView::getScrollBarPosition()
{
	return m_ppViewNode[0]->getGameObj()->getPosition();
}

gkVector3 
ScrollbarView::getScrollBarScale()
{
	return m_ppViewNode[0]->getGameObj()->getScale();
}

bool 
ScrollbarView::isHitScrollBar(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppViewNode[0]->getGameObj());
}

bool 
ScrollbarView::isHitScrollTrack(Ogre::RaySceneQueryResult& objArray)
{
	return isObjInArray(objArray,m_ppViewNode[1]->getGameObj());
}

//void 
//ScrollbarView::setVisible(bool vsb)
//{
//	if(vsb == m_bVisible)
//	{
//		return;
//	}
//	m_bVisible = vsb;
//	m_bVisible?showScrollBar():hideScrollBar();
//	return;
//}

void 
ScrollbarView::showView()
{
	m_ppBldAnm[0]->setFrameScope(_SBANM_ENTER_START_,_SBANM_ENTER_END_);
	m_ppBldAnm[1]->setFrameScope(_SBANM_ENTER_START_,_SBANM_ENTER_END_);
	m_ppBldAnm[0]->play();
	m_ppBldAnm[1]->play();

	m_ppBldTexAnm[0]->setFrameScope(_SBANM_ENTER_START_,_SBANM_ENTER_END_);
	m_ppBldTexAnm[1]->setFrameScope(_SBANM_ENTER_START_,_SBANM_ENTER_END_);
	m_ppBldTexAnm[0]->play();
	m_ppBldTexAnm[1]->play();
}

void 
ScrollbarView::hideView()
{
	m_ppBldAnm[0]->setFrameScope(_SBANM_EXIT_START_,_SBANM_EXIT_END_);
	m_ppBldAnm[1]->setFrameScope(_SBANM_EXIT_START_,_SBANM_EXIT_END_);
	m_ppBldAnm[0]->play();
	m_ppBldAnm[1]->play();

	m_ppBldTexAnm[0]->setFrameScope(_SBANM_EXIT_START_,_SBANM_EXIT_END_);
	m_ppBldTexAnm[1]->setFrameScope(_SBANM_EXIT_START_,_SBANM_EXIT_END_);
	m_ppBldTexAnm[0]->play();
	m_ppBldTexAnm[1]->play();
}

//static bool g_isFirstTime = true;
void 
ScrollbarView::onBlenderAnmFinish(BlenderAnimation* p,int s,int e)
{
	
	if(p == m_ppBldAnm[0] && s == _SBANM_ENTER_START_&& e == _SBANM_ENTER_END_)
	{
		ScrollViewImpl::getInstance()->syncScrollBar();
	}
}