//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Link.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_SHORTCUT_H)
#define _SHORTCUT_H

#include <gkScene.h>
#include <gkGameObject.h>
#include "ViewNode.h"

class Shortcut:public ViewNode
{
public:
	Shortcut(gkScene*,const gkHashedString&);
	~Shortcut();
	Shortcut setMinIndex(int i);
	Shortcut setMaxIndex(int i);
	Shortcut setIndex(int i0,int i1);
private:
	bool m_couldDelete;
};

#endif  //_SHORTCUT_H
