//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Shortcut
//  @ Date : 2012-11-6
//  @ Author : 
//
//
#include "Shortcut.h"
#include "Util.h"
#include "ViewNode.h"

Shortcut::Shortcut(gkScene* pScene,const gkHashedString& str):ViewNode(pScene,str)
{
	
}

Shortcut::~Shortcut()
{
	//if (m_pIndex)
	//{
	//	delete[] m_pIndex;
	//	m_pIndex = NULL;
	//}
}

Shortcut 
Shortcut::setIndex(int i0,int i1)
{
	m_MinIndex = i0;
	m_MaxIndex = i1;
//	m_pIndex[0] = m_MinIndex;
//	m_pIndex[1] = m_MaxIndex;
	return *this;
}

Shortcut 
Shortcut::setMinIndex(int i)
{
	m_MinIndex = i;
//	m_pIndex[0] = m_MinIndex;
	return *this;
}

Shortcut 
Shortcut::setMaxIndex(int i)
{
	m_MaxIndex = i;
//	m_pIndex[1] = m_MaxIndex;
	return *this;
}


