//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SortordView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_SORTORDVIEW_H)
#define _SORTORDVIEW_H

#include "RootView.h"

class BlenderAnimation;
class SortordView :public RootView
{
public:
	SortordView();
	~SortordView();

	void setSortordVisible(bool flag);
	bool getSortordVisible();
	bool isHitStDefault(Ogre::RaySceneQueryResult& objArray);
	bool isHitStFrequence(Ogre::RaySceneQueryResult& objArray);
	bool isHitStLetter(Ogre::RaySceneQueryResult& objArray);
	bool isFocusOnStDefault();
	bool isFocusOnStFrequence();
	bool isFocusOnHitStLetter();
	void enterAaMode();
	void exitAaMode();

	virtual void loseViewFocus();
private:
	virtual void showView();
	virtual void hideView();
private:
	ViewNode** m_ppViewNodeList ;
	BlenderAnimation** m_ppBldAnm;
	BlenderAnimation** m_ppBldTexAnm;
	BlenderAnimation** m_ppBldSecTexAnm;
	bool m_SortordVisible;		// SortTypeVisible
};

#endif  //_SORTORDVIEW_H
