//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StateBarView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_STATEBARVIEW_H)
#define _STATEBARVIEW_H

#include "RootView.h"

#define _SB_MATERIALNUM_ 9

class ViewNode;
class StateBarView :public RootView
{
public:
	StateBarView();
	~StateBarView();
	void setViewNodeMaterial(unsigned int iNodeIndex,unsigned int iMaterialIndex);
	virtual void loseViewFocus(){};
private:
	ViewNode** m_ppViewNodeList;
	Ogre::Pass*	m_pSbPass;
	int mBgTextureIDArray[_SB_MATERIALNUM_];
};

#endif  //_STATEBARVIEW_H
