//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StateBarViewImpl.h
//  @ Date : 2013年1月24日13:24:36
//  @ Author : 
//
//


#if !defined(_STATEBARVIEWIMPL_H)
#define _STATEBARVIEWIMPL_H

#include "Aabridge.h"
#include "RootViewImpl.h"
#include "gkMessageManager.h"

#define _SBIMPL_STATENUM_	5

class StateBarView;
class StateBarViewImpl :public RootViewImpl,public gkMessageManager::GenericMessageListener
{
public:
	enum eStatus
	{
		S_Netbe,
		S_USB,
		S_SD,
		S_Camera,
		S_Wifi0,
		S_Wifi1,
		S_Wifi2,
		S_Wifi3,
	};

public:
	StateBarViewImpl();
	~StateBarViewImpl();
	void syncState();
	void setState(int pos,eStatus state);
	void handleMessage(gkMessageManager::Message* message);

	virtual bool moveFocus(eFlyDirection direct){return true;};	// 移动focus
	virtual bool MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction){return true;};
private:
	gkString MessageTag;
	StateBarView* m_pStateBarView;
	char m_cStateFlag;	// S_Wifi0<<4 | Camera<<3  |  Sd<<2  | USB<<1  | NetBe
};

#endif  //_STATEBARVIEWIMPL_H
