//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StateBarView.cpp
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#include "StateBarView.h"
#include "Aabridge.h"
#include "ViewNode.h"
#include "gkEntity.h"

#define _STATEBAR_PLANE0_	"Plane_z01b01"
#define _STATEBAR_PLANE1_	"Plane_z01b02"
#define _STATEBAR_PLANE2_	"Plane_z01b03"
#define _STATEBAR_PLANE3_	"Plane_z01b04"
#define _STATEBAR_PLANE4_	"Plane_z01b05"
#define _STATEBAR_PLANE5_	"Plane_z01b06"
#define _STATEBAR_PLANE6_	"Plane_z01b07"
#define _STATEBAR_PLANE7_	"Plane_z01b08"
#define _STATEBAR_PLANE8_	"Plane_z01b09"
#define _STATEBAR_PLANE9_	"Plane_z01b10"
#define _STATEBAR_PLANENUM_	10

StateBarView::StateBarView():RootView(false)
{
	gkScene* pScene = Aabridge::getScene();
	m_ppViewNodeList = new ViewNode*[_STATEBAR_PLANENUM_];

	m_ppViewNodeList[0] = new ViewNode(pScene,_STATEBAR_PLANE0_);
	m_ppViewNodeList[1] = new ViewNode(pScene,_STATEBAR_PLANE1_);
	m_ppViewNodeList[2] = new ViewNode(pScene,_STATEBAR_PLANE2_);
	m_ppViewNodeList[3] = new ViewNode(pScene,_STATEBAR_PLANE3_);
	m_ppViewNodeList[4] = new ViewNode(pScene,_STATEBAR_PLANE4_);
	m_ppViewNodeList[5] = new ViewNode(pScene,_STATEBAR_PLANE5_);
	m_ppViewNodeList[6] = new ViewNode(pScene,_STATEBAR_PLANE6_);
	m_ppViewNodeList[7] = new ViewNode(pScene,_STATEBAR_PLANE7_);
	m_ppViewNodeList[8] = new ViewNode(pScene,_STATEBAR_PLANE8_);
	m_ppViewNodeList[9] = new ViewNode(pScene,_STATEBAR_PLANE9_);

	setViewNodeList(m_ppViewNodeList);
	setViewNodeNum(_STATEBAR_PLANENUM_);
	gkEntity*  pEntity= dynamic_cast<gkEntity*>(m_ppViewNodeList[0]->getGameObj());
	for (int i = 0;i<_SB_MATERIALNUM_;i++)
	{
		mBgTextureIDArray[i] = pEntity->getGLTextureID(0,i);
	}
}

StateBarView::~StateBarView() 
{
}

void 
StateBarView::setViewNodeMaterial(unsigned int iNodeIndex,unsigned int iMaterialIndex)
{
	_ASSERT_(iNodeIndex < _STATEBAR_PLANENUM_ && iMaterialIndex < _SB_MATERIALNUM_);
	((gkEntity*)(m_ppViewNodeList[_STATEBAR_PLANENUM_ - iNodeIndex -1]->getGameObj()))->setGLTextureID(0,0,mBgTextureIDArray[iMaterialIndex]);
}