//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Focus.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_TRANSLATIONANMINTERFACE_H)
#define _TRANSLATIONANMINTERFACE_H

class TranslationAnm;
class TranslationAnmInterface
{
public:
	virtual void onTranslationAnmFinish(TranslationAnm*) = 0;
};

#endif  //_TRANSLATIONANMINTERFACE_H
