//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.cpp
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#include "TV_Block.h"
#define _TV_BLOCK_PARENT_	"Plane_x01"
#define _TV_BLOCK_PARENTMK_	"Plane_x01c"
#define _TV_BLOCK_PLANE0_	"Plane_aa01"
#define _TV_BLOCK_PLANE1_	"Plane_aa02a01"
#define _TV_BLOCK_PLANE2_	"Plane_aa02a02"
#define _TV_BLOCK_PLANE3_	"Plane_aa02a03"
#define _TV_BLOCK_PLANE4_	"Plane_aa02a04"
#define _TV_BLOCK_PLANE5_	"Plane_aa02a05"
#define _TV_BLOCK_PLANE6_	"Plane_aaz01"
#define _TV_BLOCK_PLANENUM_	6

#define _TV_BLOCK_ANM_NAME_	"Plane_x01Action"
TVBlock::TVBlock(gkScene* pscene):Block(pscene),m_pDisableIcon(NULL)
{
	if (m_pScene)
	{
		m_ppShortcutList = new AppUnitShortcut*[_TV_BLOCK_PLANENUM_];
		m_ppShortcutList[0] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE0_))->setIndex(-3,5);
		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE1_))->setIndex(6,8);
		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE2_))->setIndex(9,11);
		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE3_))->setIndex(12,14);
		m_ppShortcutList[4] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE4_))->setIndex(15,17);
		m_ppShortcutList[5] = (new AppUnitShortcut(m_pScene,_TV_BLOCK_PLANE5_))->setIndex(18,20);
		m_ShortCutNum = _TV_BLOCK_PLANENUM_;

		m_pDisableIcon = m_pScene->getObject(_TV_BLOCK_PLANE6_);
		m_pDisableIcon->setVisible(false);
		m_BlockParentPlane = m_pScene->getObject(_TV_BLOCK_PARENT_);
		m_BlockParentPlane->setVisible(false);

		m_pBldAnm = new BlenderAnimation(m_pScene,m_BlockParentPlane,_TV_BLOCK_ANM_NAME_);
		m_pMaskPlane = m_pScene->getObject(_TV_BLOCK_PARENTMK_);
		m_pMaskPlane->setVisible(false);
	}

}

TVBlock::~TVBlock()
{
	
}


BlockEnum 
TVBlock::getBlockEnum()
{
	return TV_Block;
}


int 
TVBlock::getVacantPosParentID()
{
	return 1;
}

void TVBlock::setTVBlockEnable(bool flag)
{
	m_pDisableIcon->setVisible(!flag);
}