//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.h
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#if !defined(_TV_BLOCK_H)
#define _TV_BLOCK_H

#include "Block.h"

class TV;
class Weather;
class TVBlock:public Block
{
public:
	TVBlock(gkScene*);
	~TVBlock();
	virtual BlockEnum getBlockEnum();
	virtual int getVacantPosParentID();
	void setTVBlockEnable(bool flag);		// Ω˚÷πÕº±Í «∑Òœ‘ æ
private:
	gkGameObject* m_pDisableIcon;
	Weather* m_pWeather;
	TV*	m_pTV;
};

#endif  //_TV_BLOCK_H
