//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TV Block.cpp
//  @ Date : 2012-11-6
//  @ Author : 
//
//


#include "Videoaudio_Block.h"

#define _VA_BLOCK_PARENT_	"Plane_x04"
#define _VA_BLOCK_PARENTMK_	"Plane_x04c"
#define _VA_BLOCK_PLANE0_	"Plane_da05"	// ³©ÓÎÓ¦ÓÃ
#define _VA_BLOCK_PLANE1_	"Plane_db01"	// ÆæÒÕÓ°ÊÓ
#define _VA_BLOCK_PLANE2_	"Plane_db02"	// pptv
#define _VA_BLOCK_PLANE3_	"Plane_db03"	// ÓÅ¿áÊÓÆµ
#define _VA_BLOCK_PLANE4_	"Plane_db04"	// ËÑºüÊÓÆµ
#define _VA_BLOCK_PLANE5_	"Plane_db05"	// ÐÜÃ¨ÊÓÆµ
#define _VA_BLOCK_PLANE6_	"Plane_db06"	// pps
#define _VA_BLOCK_PLANE7_	"Plane_db07"	// dopool
#define _VA_BLOCK_PLANE8_	"Plane_db08"	// ·è¿ñ»¬Ñ©
#define _VA_BLOCK_PLANE9_	"Plane_db09"	// ÐÜÃ¨Æ¨Íõ
#define _VA_BLOCK_PLANE10_	"Plane_db10"	// ¹ÖµÁÂ³°î
#define _VA_BLOCK_PLANE11_	"Plane_db11"	// ±¦±¦µöÓã
#define _VA_BLOCK_PLANE12_	"Plane_db12"	// ÀÖÊÓÍø
#define _VA_BLOCK_ANM_NAME_ "Plane_x04Action"
#define _VA_BLOCK_PLANENUM_	13

#define _VA_BLOCK_EDITMENU_ITEM_ 1
#define _VA_BLICK_ITEM0_		"Plane_x04b1"
#define _VA_BLICK_ITEM0_ANM0_	"Plane_xa01Action.003"
#define _VA_BLICK_ITEM0_ANM1_	"Plane_xa01Action.001"
#define _VA_BLICK_ITEM0_ANM2_	"Plane_xa01bAction.002"

VideoaudioBlock::VideoaudioBlock(gkScene* pscene):Block(pscene) 
{
	if (m_pScene)
	{
		m_ppShortcutList = new AppUnitShortcut*[_VA_BLOCK_PLANENUM_];
		m_ppShortcutList[0] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE0_,NULL,true))->setIndex(-3,-1);
		m_ppShortcutList[1] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE1_))->setIndex(0,0);
		m_ppShortcutList[2] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE2_))->setIndex(1,1);
		m_ppShortcutList[3] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE3_))->setIndex(2,2);
		m_ppShortcutList[4] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE4_))->setIndex(3,3);
		m_ppShortcutList[5] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE5_))->setIndex(4,4);
		m_ppShortcutList[6] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE6_))->setIndex(5,5);
		m_ppShortcutList[7] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE7_))->setIndex(6,6);
		m_ppShortcutList[8] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE8_))->setIndex(7,7);
		m_ppShortcutList[9] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE9_))->setIndex(8,8);
		m_ppShortcutList[10] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE10_))->setIndex(9,9);
		m_ppShortcutList[11] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE11_))->setIndex(10,10);
		m_ppShortcutList[12] = (new AppUnitShortcut(m_pScene,_VA_BLOCK_PLANE12_))->setIndex(11,11);

		m_ShortCutNum = _VA_BLOCK_PLANENUM_;
		m_BlockParentPlane = m_pScene->getObject(_VA_BLOCK_PARENT_);
		m_BlockParentPlane->setVisible(false);
		m_pBldAnm = new BlenderAnimation(m_pScene,m_BlockParentPlane,_VA_BLOCK_ANM_NAME_);
		m_pMaskPlane = m_pScene->getObject(_VA_BLOCK_PARENTMK_);
		m_pMaskPlane->setVisible(false);
		setXVisible(false);
#if !_LAUNCHER_EDITMENU_OLDSTYLE_
		initEditMenu();
#endif
	}
}

VideoaudioBlock::~VideoaudioBlock() 
{
	ui_deleteArray(m_ppMenuAnmList,_BLOCK_EDITMENU_ANM_*_VA_BLOCK_EDITMENU_ITEM_);
}

BlockEnum
VideoaudioBlock::getBlockEnum()
{
	return Video_Block;
}


int 
VideoaudioBlock::getMenuFlag()
{
	return 1;
}

int 
VideoaudioBlock::getVacantPosParentID()
{
	return 4;
}

void 
VideoaudioBlock::initEditMenu()
{
	m_MenuItemNum = _VA_BLOCK_EDITMENU_ITEM_;
	m_MenuItemFocus = 0;

	m_ppMenuAnmList = new BlenderAnimation*[_BLOCK_EDITMENU_ANM_*_VA_BLOCK_EDITMENU_ITEM_];
	m_ppMenuAnmList[0] = new BlenderAnimation(m_pScene,m_pScene->getObject(_VA_BLICK_ITEM0_),_VA_BLICK_ITEM0_ANM0_);
	m_ppMenuAnmList[1] = new BlenderAnimation(m_pScene,m_pScene->getObject(_VA_BLICK_ITEM0_),_VA_BLICK_ITEM0_ANM1_);
	m_ppMenuAnmList[2] = new BlenderAnimation(m_pScene,m_pScene->getObject(_VA_BLICK_ITEM0_),_VA_BLICK_ITEM0_ANM2_);
	m_ppMenuAnmList[0]->setAnmInterface(this);

	m_ppMenuObjList = new gkGameObject*[_VA_BLOCK_EDITMENU_ITEM_];
	m_ppMenuObjList[0] = m_pScene->getObject(_VA_BLICK_ITEM0_);
	m_ppMenuObjList[0]->setVisible(false);
}