//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WallpaperView.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_WALLPAPERVIEW_H)
#define _WALLPAPERVIEW_H

#include "RootView.h"
#include "BlenderAnmInterface.h"

class ViewNode;
class BlenderAnimation;
class WallpaperView :public RootView,public BlenderAnmInterface
{
public:
	WallpaperView();
	~WallpaperView();
	bool isHitWpSetButton(Ogre::RaySceneQueryResult& hitList);
	ViewNode* getCurrentViewNode();	
	int getWallpaperNodeIndex();
	virtual bool setFocus(ViewNode* node);
	virtual bool setFocus(int index);
	virtual void loseViewFocus(){};
	virtual void onBlenderAnmFinish(BlenderAnimation* p,int s,int e);
private:
	virtual void showView();
	virtual void hideView();
private:
	ViewNode* m_pWallpaperNode;
	ViewNode** m_ppViewNodeList;
	BlenderAnimation** m_ppAnmList;
};

#endif  //_WALLPAPERVIEW_H
