//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HaResidentViewImpl.h
//  @ Date : 2012-11-20
//  @ Author : 
//
//


#if !defined(_WALLPAPERVIEWIMPL_H)
#define _WALLPAPERVIEWIMPL_H

#include "Aabridge.h"
#include "RootViewImpl.h"

#define _WP_BG_MATERIALNUM_	5

class WallpaperView;
class WallpaperViewImpl :public RootViewImpl
{
public:
	WallpaperViewImpl();
	~WallpaperViewImpl();
	bool isHitWpSetButton(Ogre::RaySceneQueryResult& hitList);
	ViewNode* getCurrentViewNode();	
	int getWallPaperThumbIndex();
	void setWallpaper(int index);
	bool isFocusOnWpSetButton();
	
	bool setViewNodeFocus(ViewNode*);		// 设置viewNode* 为当前focus
	virtual bool moveFocus(eFlyDirection direct);	// 移动focus
	virtual bool MoveViewFocus(RootViewImpl* pPreImpl,eFlyDirection direction){return true;};
private:
	WallpaperView* m_pWallpaperView;
	Ogre::Pass*	m_pBgPass;
	int mBgMaterialArray[_WP_BG_MATERIALNUM_];
};

#endif  //_WALLPAPERVIEWIMPL_H
